### ISSUE TITLE
The RAM

### ISSUE THREAD

**Issue by STSTERANDMOMO** [Lu-Feng/SelaVPR#2]
Thank you for sharing your work, your paper was very interesting and the results are also very impressive!When I trained the pre-trained model on the msls datasets,I met the following problem.Because the RAM was out of memory,my programa was killed by the system.How can I solve the issue?

**Comment by STSTERANDMOMO** [comment]
Are there any variables in your program that are accumulating without being deleted, causing them to continuously occupy a large amount of memory?How can I to find it?

**Comment by Lu-Feng** [comment]
Sorry for the late reply. Since our training program runs a test on val after each epoch, I need to know if the interruption occurred during training or testing. We use an image with a large number of local features (61x61), and when the dataset has a large number of images, RAM may out of memory. This also happened when we ran multiple test programs at the same time.

**Comment by Lu-Feng** [comment]
Okay, I get it. I think this is mainly caused by our program reading all extracted local features into RAM at once. It can be solved by first saving the extracted local features, and loading only the local features currently needed for local matching into RAM each time. I'll be working on this in the coming days.

**Comment by STSTERANDMOMO** [comment]
Thank you for your answer! Wishing your greater achievements in the upcoming research!

**Comment by Lu-Feng** [comment]
Hi @STSTERANDMOMO , I have added the test_efficient_ram_usage function in test.py to address this issue. You can use it simply by adding "--efficient_ram_testing" to the (train or test) run command, such as
```
python3 eval.py --datasets_folder=/path/to/your/datasets_vg/datasets --dataset_name=pitts30k --resume=/path/to/finetuned/pitts30k/model/SelaVPR_pitts30k.pth --rerank_num=100 --efficient_ram_testing
```

**Comment by VEDFU** [comment]
@STSTERANDMOMO   老哥能不能贴一下训练和推理的速度相关信息，或者给一下Pitts30和MSLS数据下载链接（官方链接都下载不下来）

**Comment by Lu-Feng** [comment]
@VEDFU The official download link: [Pitts30k](https://data.ciirc.cvut.cz/public/projects/2015netVLAD/), [MSLS](https://www.mapillary.com/dataset/places). You can format these datasets following this [repo](https://github.com/gmberton/VPR-datasets-downloader).

**Comment by STSTERANDMOMO** [comment]
@Lu-Feng Following the VPR-datasets-downloader Repo，My msls-val has 10000+ images different from your instruction.How can I get the same msls-val as your experiment.

**Comment by STSTERANDMOMO** [comment]
@Lu-Feng Can you upload your msls-val data to Baidu Netdisk or Google Drive?

**Comment by Lu-Feng** [comment]
The details of MSLS-val have been discussed in this [issue](https://github.com/Lu-Feng/SelaVPR/issues/1#issuecomment-2003711490). We used the official MSLS-val dataset (740 query images) but I'm not sure if I can distribute it according its license. The key (name) of query images can be obtained [here](https://github.com/Lu-Feng/MSLS-val). You can copy these 740 query images from your 10000+ query images based on the key/name. You can also add me on WeChat (1600925872) if you need more help.
